### ISSUE TITLE
Couldn't build android APK, says could not find ANDROID ndk

### ISSUE THREAD

**Issue by praptobala** [dahburj/Barracuda-PoseNet#3]
WHEN building ANDROD APK, It says NDK root is missing, but I have set the NDK path in Env. variable. But still it shows error as this,

Android clang version 5.0.300080  (based on LLVM 5.0.300080)
Target: armv7a--linux-android
Thread model: posix
InstalledDir: C:\Program Files\Unity\Hub\Editor\2019.1.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin
clang.exe: error: no such file or directory: 'Files/Unity/Hub/Editor/2019.1.7f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK\platforms\android-16\arch-arm'
clang.exe: error: no such file or directory: 'Files/Unity/Hub/Editor/2019.1.7f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64'

**Comment by dahburj** [comment]
Did you download the NDK from unity hub?

**Comment by dahburj** [comment]
Go to the external preferences settings and see what the file path is set to for your ndk and sdk, before unity hub started including it with the install of Unity, I would have to download the NDK seperatly from the sdk, as unity uses an older version than the one Android studio downloads. If you have unity hub go to your installs and click on the unity version you're using, then click "Add Modules" and install the Android sdk & ndk under "Android Build Support". Then under your external preferences make sure check SDK/NDK included with unity for everything you've added, Unity should auto fill that path, which you can confirm by unchecking the Included with unity options to make the path that was auto inserted visible.

**Comment by praptobala** [comment]
Yes, I gave proper NDK/SDK folder path. But still throws error. It seems to be taking a wrong path,

Target: armv7a--linux-android
Thread model: posix
InstalledDir: C:\Program Files\Unity\Hub\Editor\2019.1.7f1\Editor\Data\PlaybackEngines\AndroidPlayer\NDK\toolchains\llvm\prebuilt\windows-x86_64\bin
clang.exe: error: no such file or directory: 'Files/Unity/Hub/Editor/2019.1.7f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK\platforms\android-16\arch-arm'
clang.exe: error: no such file or directory: 'Files/Unity/Hub/Editor/2019.1.7f1/Editor/Data/PlaybackEngines/AndroidPlayer/NDK\toolchains\arm-linux-androideabi-4.9\prebuilt\windows-x86_64'

**Comment by murtaza98** [comment]
@dahburj can this project run on android os?

**Comment by dahburj** [comment]
@murtaza98 I have no issues building it to Android, I've even gotten it running on my own custom compiled Android OS, Pixel3 (Google Android OS), Samsung S6 EdgePlus, Samsung S7 Edge, as well iOS (iPhoneX, iPhone8, iPad) and Mac stand alone. I'm sorry I couldn't help you with your error @Praptobala, try cloning the latest commit and see if you get the same errors. The problem I see from the error above is your file path is getting twisted into dropping the necessary Windows OS "C://" prefix, and considering it is a clang error one can only wonder if it's because your installed clang version is mismatching the NDK's (Android-16) required version, or configured incorrectly. Have you tried predefining the correct Make/CMake headers somewhere in your environment variables or MakeFile?

**Comment by konsnos** [comment]
Works well on Samsung S8, and A40 too, with the NDK installed by Unity Hub and Unity version 2019.4.0f1 in Windows 10, and a hack to fix #8 .

I've also tried to change Scripting Backend to IL2CPP and API Compatibility Level to .NET 4.x and add the ARM64 architecture and works with these settings too.
